CREATE SEQUENCE SEQ_DOCUMENTOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE DOCUMENTOS(
    ID INTEGER DEFAULT SEQ_DOCUMENTOS.NEXTVAL,
    NOME VARCHAR2(100),
    EXTENSAO VARCHAR2(100),
    DATA_ENVIO DATE
);